apiVersion: batch/v1
kind: Job
metadata:
  name: taskboard-migrate
  namespace: taskboard-lab
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 180
  template:
    metadata:
      labels:
        app: taskboard-migrate
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: migrate
          image: tbank-sre-taskboard:hw02
          imagePullPolicy: Never
          args: [migrate]
          envFrom:
            - configMapRef:
                name: taskboard-config
            - secretRef:
                name: taskboard-secrets
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 64Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
